import { app, BrowserWindow, dialog, ipcMain, shell } from 'electron'
import { join } from 'path'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs'
import * as db from './database'
import { tailorDocument, generateFollowUpMessage, regenerateSection, verifyDocumentContent, scoreJobFit, RateLimitError } from './ai'
import { scrapeJobFromUrl } from './jobScraper'
import { scanAllBoards, BOARDS } from './jobSearch'
import { formatLocation } from './utils'
import { startQueueProcessor, stopQueueProcessor, enqueue } from './aiQueue'
import { scheduleNextAutoScan, cancelAutoScan, markScanStarted, markScanCompleted, restartAutoScanTimer } from './autoScan'
import type {
  ApiModelConfig,
  Application,
  CreateJobInput,
  FollowUp,
  Interview,
  Job,
  JobStatus,
  ScanFilters,
  ScanResult,
  Settings,
  TailorRequest
} from './types'

// Module-level scan state — survives tab switches in the renderer
let _scanState: { scanning: boolean; progress: string[]; result: ScanResult | null; startedAt: number | null } = {
  scanning: false,
  progress: [],
  result: null,
  startedAt: null
}

function createWindow(): void {
  const mainWindow = new BrowserWindow({
    width: 1280,
    height: 860,
    minWidth: 960,
    minHeight: 640,
    show: false,
    title: 'Apply Assistant',
    titleBarStyle: 'hiddenInset',
    backgroundColor: '#0f1117',
    webPreferences: {
      preload: join(__dirname, '../preload/index.js'),
      sandbox: true,
      contextIsolation: true,
      nodeIntegration: false
    }
  })

  mainWindow.on('ready-to-show', () => {
    mainWindow.show()
  })

  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    shell.openExternal(url)
    return { action: 'deny' }
  })

  if (process.env.ELECTRON_RENDERER_URL) {
    mainWindow.loadURL(process.env.ELECTRON_RENDERER_URL)
  } else {
    mainWindow.loadFile(join(__dirname, '../renderer/index.html'))
  }
}

function registerIpc(): void {
  ipcMain.handle('dashboard:stats', () => db.getDashboardStats())

  ipcMain.handle('jobs:list', (_e, status?: JobStatus) => db.listJobs(status))
  ipcMain.handle('jobs:get', (_e, id: number) => db.getJob(id))
  ipcMain.handle('jobs:create', (_e, input: CreateJobInput) => {
    const dup = db.findDuplicateJob(input)
    if (dup) throw new Error(`Job already exists: ${dup.company} — ${dup.title}`)
    const job = db.createJob(input)
    autoGenerateDocuments(job)
    return job
  })
  ipcMain.handle('jobs:update', (_e, id: number, fields: Partial<CreateJobInput & { status: JobStatus }>) =>
    db.updateJob(id, fields)
  )
  ipcMain.handle('jobs:delete', (_e, id: number) => db.deleteJob(id))
  ipcMain.handle('jobs:search', (_e, query: string) => db.searchJobs(query))
  ipcMain.handle('jobs:importFromUrl', async (_e, url: string) => {
    const input = await scrapeJobFromUrl(url)
    const dup = db.findDuplicateJob(input)
    if (dup) throw new Error(`Job already exists: ${dup.company} — ${dup.title}`)
    const job = db.createJob(input)
    autoGenerateDocuments(job)
    return job
  })

  ipcMain.handle('jobs:batchScore', async () => {
    const settings = db.getSettings()
    const baseCv = settings.base_cv || ''
    const currentVersion = settings.cv_version ?? 0
    const jobs = db.listJobs()
    let updated = 0
    for (const job of jobs) {
      // Only re-score jobs that have never been scored, or whose score was
      // computed against a previous version of the base CV.
      const needsScore = job.score == null || job.fit_score_version !== currentVersion
      if (!needsScore) continue
      if (!baseCv) {
        // No CV configured; keep the row at neutral but mark it as scored
        // against the current CV version so we don't retry every load.
        db.updateJob(job.id, {
          score: 0.5,
          fit_rationale: 'No base CV configured.',
          fit_breakdown: { matched_skills: [], missing_skills: [], experience_years_match: null },
          fit_score_version: currentVersion
        })
        updated++
        continue
      }
      try {
        const fit = await scoreJobFit({
          title: job.title,
          description: job.description,
          requirements: job.requirements,
          baseCv
        })
        if (fit.source === 'heuristic') {
          // LLM call failed. Do NOT overwrite any existing real fit score with
          // a heuristic fallback. Persist only the error so the user can see
          // why the scorer is broken.
          db.updateJob(job.id, {
            fit_last_error: fit.error || 'LLM scorer fell back to heuristic.'
          })
          console.warn(`[fit] job ${job.id} (${job.company} — ${job.title}): ${fit.error || 'heuristic fallback'}`)
        } else {
          db.updateJob(job.id, {
            score: fit.score,
            fit_rationale: fit.rationale,
            fit_breakdown: fit.breakdown,
            fit_score_version: currentVersion,
            fit_last_error: null
          })
          updated++
        }
      } catch (err) {
        // Don't silently swallow — surface the error and leave the row alone.
        const msg = err instanceof Error ? err.message : 'Unknown error'
        console.warn(`[fit] job ${job.id} (${job.company} — ${job.title}): ${msg}`)
        db.updateJob(job.id, { fit_last_error: msg })
      }
    }
    return { updated }
  })

  ipcMain.handle('jobs:recomputeFit', async (_e, id: number) => {
    const job = db.getJob(id)
    if (!job) throw new Error('Job not found')
    const settings = db.getSettings()
    const baseCv = settings.base_cv || ''
    const currentVersion = settings.cv_version ?? 0
    if (!baseCv) {
      return db.updateJob(id, {
        score: 0.5,
        fit_rationale: 'No base CV configured.',
        fit_breakdown: { matched_skills: [], missing_skills: [], experience_years_match: null },
        fit_score_version: currentVersion,
        fit_last_error: null
      })
    }
    const fit = await scoreJobFit({
      title: job.title,
      description: job.description,
      requirements: job.requirements,
      baseCv
    })
    if (fit.source === 'heuristic') {
      // Don't pretend a heuristic fallback is a real fit score.
      const errMsg = fit.error || 'LLM scorer fell back to heuristic.'
      console.warn(`[fit] job ${id}: ${errMsg}`)
      return db.updateJob(id, { fit_last_error: errMsg })
    }
    return db.updateJob(id, {
      score: fit.score,
      fit_rationale: fit.rationale,
      fit_breakdown: fit.breakdown,
      fit_score_version: currentVersion,
      fit_last_error: null
    })
  })

  ipcMain.handle('jobs:backfillDates', () => db.backfillJobPostingDates())

  ipcMain.handle('jobs:scanBoards', async (e, filters?: ScanFilters) => {
    _scanState.scanning = true
    _scanState.progress = []
    _scanState.result = null
    _scanState.startedAt = Date.now()
    markScanStarted()
    try {
      const result = await scanAllBoards(filters, (msg) => {
        _scanState.progress.push(msg)
        e.sender.send('scan:progress', msg)
      }, autoGenerateDocuments)
      _scanState.result = result
      markScanCompleted()
      // Notify all renderers that the scan has completed
      for (const win of BrowserWindow.getAllWindows()) {
        if (!win.isDestroyed()) win.webContents.send('scan:complete', result)
      }
      return result
    } finally {
      _scanState.scanning = false
      _scanState.startedAt = null
    }
  })

  ipcMain.handle('scan:status', () => ({
    scanning: _scanState.scanning,
    progress: [..._scanState.progress],
    result: _scanState.result,
    startedAt: _scanState.startedAt
  }))

  ipcMain.handle('scan:clearResult', () => {
    _scanState.result = null
    _scanState.progress = []
  })

  ipcMain.handle('documents:list', (_e, jobId?: number) => db.listDocuments(jobId))
  ipcMain.handle('documents:create', (_e, type: 'cv' | 'cover_letter', title: string, content: string, jobId?: number) => {
    const doc = db.createDocument(type, title, content, jobId)
    if (jobId) db.recomputeJobStatusFromDocs(jobId)
    return doc
  })
  ipcMain.handle('documents:update', (_e, id: number, title: string, content: string) => {
    const doc = db.updateDocument(id, title, content)
    if (doc.job_id) db.recomputeJobStatusFromDocs(doc.job_id)
    return doc
  })
  ipcMain.handle('documents:delete', (_e, id: number) => {
    // Capture the doc's job_id before deletion so we can recompute after.
    const docs = db.listDocuments()
    const target = docs.find((d) => d.id === id)
    db.deleteDocument(id)
    if (target?.job_id) db.recomputeJobStatusFromDocs(target.job_id)
  })
  ipcMain.handle('documents:verify', async (_e, jobId: number, documentId: number, docType: 'cv' | 'cover_letter') => {
    try {
      const result = await verifyDocumentContent(jobId, documentId, docType)
      db.recomputeJobStatusFromDocs(jobId)
      return result
    } catch (err) {
      if (err instanceof RateLimitError) {
        enqueue({ type: 'verify', jobId, documentId })
        return { queued: true } as any
      }
      throw err
    }
  })
  ipcMain.handle('documents:regenerateSection', async (_e, documentId: number, sectionName: string, jobId: number, extraContext?: string) => {
    try {
      return await regenerateSection(documentId, sectionName, jobId, extraContext)
    } catch (err) {
      if (err instanceof RateLimitError) {
        enqueue({ type: 'regenerate_section', jobId, documentId, sectionName, extraContext })
        return { queued: true }
      }
      throw err
    }
  })
  ipcMain.handle('documents:exportPdf', async (_e, title: string, content: string, docType?: string, company?: string, position?: string) => {
    const win = new BrowserWindow({ show: false, webPreferences: { contextIsolation: true, nodeIntegration: false } })

    function stripMarkdown(s: string): string {
      return s.replace(/\*\*(.+?)\*\*/g, '$1').replace(/\*(.+?)\*/g, '$1').replace(/__(.+?)__/g, '$1').replace(/_(.+?)_/g, '$1')
    }

    const sectionHeaders = new Set([
      'professional summary', 'summary', 'profile',
      'core competencies', 'competencies', 'skills', 'qualifications', 'technical skills',
      'professional experience', 'experience', 'work history', 'work experience',
      'education',
      'certifications', 'languages', 'interests', 'skills & interests', 'skills and interests',
      'projects', 'project experience',
      'leadership & activities', 'leadership and activities', 'activities', 'leadership',
      'publications', 'honors & awards', 'honors and awards', 'awards',
      'additional information', 'additional'
    ])

    function isHeader(s: string): boolean {
      const cleaned = stripMarkdown(s).toLowerCase().trim()
      return sectionHeaders.has(cleaned) || /^[a-z\s&]+$/.test(cleaned) && sectionHeaders.has(cleaned.replace(/[^a-z\s&]/g, '').trim())
    }

    const lines = content.split('\n')
    let htmlBody = ''
    let headerCollected = false
    const headerLines: string[] = []
    let noBulletSection = false

    function esc(s: string) {
      return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    }

    const bulletVerbs = /^(accomplished|achieved|led|managed|developed|created|implemented|designed|built|launched|delivered|improved|reduced|increased|generated|established|negotiated|coordinated|directed|spearheaded|introduced|optimized|transformed|piloted|engineered|produced|executed|authored|published|presented|mentored|trained|recruited|hired|fostered|cultivated|prepared|conducted|analyzed|analysed|evaluated|assessed|facilitated|collaborated|organized|supervised|overhauled|streamlined|consolidated|architected|championed|drove|drafted|formulated|identified|integrated|maintained|monitored|performed|pioneered|promoted|recommended|scheduled|secured|solved|standardized|strengthened|taught|wrote)/i
    const noBulletSections = new Set(['skills & interests', 'skills and interests', 'skills', 'interests', 'certifications', 'languages', 'additional information', 'additional'])

    function splitTab(label: string, rest: string): [string, string] {
      return [label.replace(/^\*+|\*+$/g, '').trim(), rest.trim()]
    }

    // Detect right-aligned suffix separated by 3+ spaces:
    //   "Title    Month Year – Month Year"   (date range)
    //   "Org      City, State"               (location)
    // Location side: "City, ST" or "City, ST Zip" or "City, Country"
    const dateRangeRe = /\s{3,}\b([A-Z][a-z]+\.?\s+\d{4}\s*[–\-—]+\s*(?:[A-Z][a-z]+\.?\s+\d{4}|Present)|[A-Z][a-z]+\.?\s+\d{4})\b$/
    const locationSuffixRe = /\s{3,}\b([A-Z][^,]{2,30},\s*(?:[A-Z]{2}|[A-Z][a-z]+)(?:\s+\d{5})?)$/

    // Looser date-range check (any whitespace run) used for next-line lookahead.
    const dateRangeAnyRe = /\b([A-Z][a-z]+\.?\s+\d{4}\s*[–\-—]+\s*(?:[A-Z][a-z]+\.?\s+\d{4}|Present)|[A-Z][a-z]+\.?\s+\d{4})\b\s*$/
    // Loose location suffix on an org line (single space ok): "Org City, ST" / "Org City, Country"
    const orgLocationLooseRe = /,\s*(?:[A-Z]{2}|[A-Z][a-z]+)(?:\s+\d{5})?$/

    for (let i = 0; i < lines.length; i++) {
      const raw = lines[i]
      const trimmed = raw.trim()
      const cleaned = stripMarkdown(trimmed).trim()
      if (!cleaned) { htmlBody += '<div class="spacer"></div>\n'; continue }

      const sect = isHeader(trimmed)
      const hasTab = cleaned.includes('\t')
      const hasMultiSpace = dateRangeRe.test(cleaned) || locationSuffixRe.test(cleaned)
      const isBullet = /^[•\-*\d+.)\]\s]/.test(cleaned) || bulletVerbs.test(cleaned)

      // Look-ahead: next non-empty line looks like a date range? Then current is an org line.
      let nextClean = ''
      for (let j = i + 1; j < lines.length && j < i + 4; j++) {
        const nc = stripMarkdown(lines[j].trim()).trim()
        if (!nc) continue
        nextClean = nc
        break
      }
      const nextIsDateLine = nextClean && (dateRangeRe.test(nextClean) || dateRangeAnyRe.test(nextClean))
      const looksLikeOrgLine = !hasTab && !hasMultiSpace && !isBullet && !!nextIsDateLine && orgLocationLooseRe.test(cleaned)
      const looksLikeTitleLine = !hasTab && !hasMultiSpace && !isBullet && dateRangeAnyRe.test(cleaned) && cleaned !== nextClean

      if (sect) {
        const lower = stripMarkdown(trimmed).toLowerCase().trim()
        noBulletSection = noBulletSections.has(lower)
        if (!headerCollected) headerCollected = true
        htmlBody += `<div class="section-header">${esc(cleaned)}</div>\n`
        continue
      }

      if (!headerCollected) {
        if (isBullet) {
          headerCollected = true
        } else {
          if (headerLines.length < 3) { headerLines.push(cleaned); continue }
          else { headerCollected = true }
        }
      }

      if (isBullet) { htmlBody += `<div class="bullet">${esc(cleaned.replace(/^[•\-\*\d+.)\]\s]+/, ''))}</div>\n`; continue }

      if (hasTab) {
        const parts = cleaned.split('\t')
        const [label, rest] = splitTab(parts[0], parts.slice(1).join(' '))
        htmlBody += `<div class="split-line"><span class="left">${esc(label)}</span><span class="right">${esc(rest)}</span></div>\n`
      } else if (hasMultiSpace) {
        const m = cleaned.match(dateRangeRe) || cleaned.match(locationSuffixRe)!
        const label = cleaned.slice(0, m.index).replace(/^\*+|\*+$/g, '').trim()
        const rest = cleaned.slice(m.index).replace(/^\s+/, '').trim()
        htmlBody += `<div class="split-line"><span class="left">${esc(label)}</span><span class="right">${esc(rest)}</span></div>\n`
      } else if (looksLikeOrgLine) {
        // Split off location suffix (last ", XX" chunk) as the right-aligned side.
        const m = cleaned.match(orgLocationLooseRe)!
        const label = cleaned.slice(0, m.index).replace(/,\s*$/, '').trim()
        const rest = cleaned.slice(m.index).replace(/^,\s*/, '').trim()
        htmlBody += `<div class="split-line"><span class="left">${esc(label)}</span><span class="right">${esc(rest)}</span></div>\n`
      } else if (looksLikeTitleLine) {
        // Title line with embedded date range (no wide gap, no tab). Split at date start.
        const m = cleaned.match(dateRangeAnyRe)!
        const label = cleaned.slice(0, m.index).replace(/,\s*$/, '').trim()
        const rest = cleaned.slice(m.index).trim()
        htmlBody += `<div class="split-line"><span class="left">${esc(label)}</span><span class="right">${esc(rest)}</span></div>\n`
      } else if (cleaned.includes('|') && cleaned.length < 120) {
        const parts = cleaned.split('|').map(s => s.replace(/^\*+|\*+$/g, '').trim())
        htmlBody += `<div class="split-line"><span class="left">${esc(parts[0])}</span><span class="right">${esc(parts.slice(1).join(' | '))}</span></div>\n`
      } else if (noBulletSection) {
        htmlBody += `<div class="body-line">${esc(cleaned)}</div>\n`
      } else {
        htmlBody += `<div class="bullet">${esc(cleaned)}</div>\n`
      }
    }

    const headerHtml = headerLines.length > 0
      ? `<div class="header">${headerLines.map((l, j) => j === 0 ? `<div class="name">${esc(l)}</div>` : `<div class="contact">${esc(l)}</div>`).join('\n')}</div>`
      : ''

    const fullHtml = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>
  @page { margin: 0.6in 0.7in; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: Calibri, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 11pt; line-height: 1.2; color: #000; }
  .header { text-align: center; margin-bottom: 10px; }
  .name { font-size: 12pt; font-weight: bold; }
  .contact { font-size: 10pt; color: #222; }
  .section-header { text-align: center; font-weight: bold; font-size: 11pt; margin-top: 12px; margin-bottom: 3px; }
  .split-line { margin-bottom: 1px; }
  .split-line .left { font-weight: bold; }
  .split-line .right { float: right; }
  .bullet { margin-bottom: 1px; padding-left: 20px; text-indent: -10px; }
  .bullet::before { content: "• "; }
  .body-line { margin-bottom: 1px; }
  .spacer { height: 6px; }
</style></head>
<body>
${headerHtml}
${htmlBody}
</body>
</html>`
    await win.loadURL('data:text/html;charset=utf-8,' + encodeURIComponent(fullHtml))
    const pdf = await win.webContents.printToPDF({})
    win.close()
    const settings = db.getSettings()
    const userName = (settings.user_name || '').replace(/[^a-zA-Z0-9]/g, '')
    const safe = (s: string) => s.replace(/[^a-zA-Z0-9]/g, '')
    const nameParts = [userName, company ? safe(company) : '', position ? safe(position) : '', docType || title.replace(/ .*/, '')].filter(Boolean)
    const fileName = (nameParts.length > 1 ? nameParts.join('_') : `${title.replace(/[^a-z0-9]/gi, '_')}`) + '.pdf'
    const docsDir = join(app.getAppPath(), 'docs')
    if (!existsSync(docsDir)) mkdirSync(docsDir, { recursive: true })
    const { canceled, filePath } = await dialog.showSaveDialog({
      title: 'Save PDF',
      defaultPath: join(docsDir, fileName),
      filters: [{ name: 'PDF', extensions: ['pdf'] }]
    })
    if (canceled || !filePath) return null
    writeFileSync(filePath, pdf)
    return filePath
  })

  ipcMain.handle('applications:list', () => db.listApplications())
  ipcMain.handle('applications:getOrCreate', (_e, jobId: number) => db.getOrCreateApplication(jobId))
  ipcMain.handle('applications:update', (_e, id: number, fields: Partial<Application>) =>
    db.updateApplication(id, fields)
  )
  ipcMain.handle(
    'applications:markApplied',
    (_e, id: number, method: string, email?: string, name?: string) =>
      db.markApplied(id, method, email, name)
  )

  ipcMain.handle('followUps:list', (_e, includeCompleted?: boolean) =>
    db.listFollowUps(includeCompleted)
  )
  ipcMain.handle('followUps:create', (_e, appId: number, dueDate: string, type: FollowUp['type'], message?: string) =>
    db.createFollowUp(appId, dueDate, type, message)
  )
  ipcMain.handle('followUps:complete', (_e, id: number) => db.completeFollowUp(id))
  ipcMain.handle('followUps:generateMessage', async (_e, company: string, title: string, days: number) =>
    generateFollowUpMessage(company, title, days)
  )

  ipcMain.handle('interviews:list', (_e, upcomingOnly?: boolean) => db.listInterviews(upcomingOnly))
  ipcMain.handle(
    'interviews:create',
    (
      _e,
      appId: number,
      scheduledAt: string,
      type: Interview['type'],
      duration?: number,
      location?: string,
      interviewer?: string,
      notes?: string
    ) => db.createInterview(appId, scheduledAt, type, duration, location, interviewer, notes)
  )
  ipcMain.handle('interviews:update', (_e, id: number, fields: Partial<Interview>) =>
    db.updateInterview(id, fields)
  )

  ipcMain.handle('settings:get', () => db.getSettings())
  ipcMain.handle('settings:update', (_e, partial: Partial<Settings>) => {
    const result = db.updateSettings(partial)
    // Re-schedule auto-scan if the relevant settings changed
    if ('auto_scan_enabled' in partial || 'auto_scan_interval_minutes' in partial) {
      restartAutoScanTimer()
    }
    return result
  })
  ipcMain.handle('settings:reset', () => db.resetSettings())

  ipcMain.handle('models:list', () => db.listApiModels())
  ipcMain.handle('models:save', (_e, models: ApiModelConfig[]) => db.saveApiModels(models))
  ipcMain.handle('models:add', (_e, model: Omit<ApiModelConfig, 'id'>) => db.addApiModel(model))
  ipcMain.handle('models:delete', (_e, id: string) => db.deleteApiModel(id))

  ipcMain.handle('ai:tailor', async (_e, request: TailorRequest) => {
    try {
      return await tailorDocument(request)
    } catch (err) {
      if (err instanceof RateLimitError) {
        enqueue({ type: request.document_type === 'cv' ? 'generate_cv' : 'generate_cover_letter', jobId: request.job_id })
        return { queued: true }
      }
      throw err
    }
  })

  ipcMain.handle('db:clearSeenUrls', () => db.clearSeenUrls())
  ipcMain.handle('db:clearAllData', () => db.clearAllData())

  ipcMain.handle('db:retrofitLocations', () => {
    const result = db.retrofitLocations()
    return result
  })

  ipcMain.handle('db:exportAll', async () => {
    const { canceled, filePath } = await dialog.showSaveDialog({
      title: 'Export all data',
      defaultPath: join(app.getPath('userData'), `apply-assistant-export-${new Date().toISOString().slice(0, 10)}.json`),
      filters: [{ name: 'JSON', extensions: ['json'] }]
    })
    if (canceled || !filePath) return null
    writeFileSync(filePath, JSON.stringify(db.exportAllData(), null, 2))
    return filePath
  })

  ipcMain.handle('security:status', () => db.encryptionStatus())

  // AI Queue
  ipcMain.handle('aiQueue:list', () => db.getAIQueue())

  ipcMain.handle('boards:list', () => {
    return BOARDS.map((b) => ({ name: b.name, useBrowser: b.useBrowser }))
  })
  ipcMain.handle('boards:health', () => db.getBoardHealth())
  ipcMain.handle('aiQueue:retry', (_e, id: number) => {
    db.updateAIQueueItem(id, { status: 'pending', nextRetryAt: Date.now(), lastError: undefined })
    return db.getAIQueue()
  })
  ipcMain.handle('aiQueue:remove', (_e, id: number) => {
    db.removeAIQueueItem(id)
    return db.getAIQueue()
  })

  ipcMain.handle('shell:openExternal', (_e, url: string) => {
    if (typeof url !== 'string') return
    let parsed: URL
    try {
      parsed = new URL(url)
    } catch {
      return
    }
    if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') return
    return shell.openExternal(url)
  })
}

async function autoGenerateDocuments(job: Job): Promise<void> {
  try {
    const app = db.getOrCreateApplication(job.id)
    const [cvResult, clResult] = await Promise.all([
      tailorDocument({ job_id: job.id, document_type: 'cv' }),
      tailorDocument({ job_id: job.id, document_type: 'cover_letter' })
    ])
    db.updateApplication(app.id, {
      cv_document_id: cvResult.document_id,
      cover_letter_document_id: clResult.document_id
    })

    // Verify and regenerate each document until score > 70
    for (const [docId, docType] of [[cvResult.document_id, 'cv' as const], [clResult.document_id, 'cover_letter' as const]]) {
      let bestDocId = docId
      let prevFeedback = ''
      // Safety cap so a misbehaving verifier can't loop forever.
      const MAX_ATTEMPTS = 5
      for (let attempt = 0; attempt < MAX_ATTEMPTS; attempt++) {
        const v = await verifyDocumentContent(job.id, bestDocId, docType)
        if (v.kind === 'skip') {
          // Doc was deleted mid-flight, or the AI response couldn't be parsed.
          // Nothing to regenerate from — stop the loop and leave the existing
          // (non-existent or previously scored) document alone.
          break
        }
        if (v.passed) break
        prevFeedback = v.feedback
        // Regenerate with the verification feedback as extra context
        const retry = await tailorDocument({
          job_id: job.id,
          document_type: docType,
          base_content: `Previous version had these issues: ${v.feedback}\n\n---\n${db.getDocument(bestDocId)?.content || ''}`
        })
        bestDocId = retry.document_id
      }
      // Point the application to the best version
      if (docType === 'cv') {
        db.updateApplication(app.id, { cv_document_id: bestDocId })
      } else {
        db.updateApplication(app.id, { cover_letter_document_id: bestDocId })
      }
    }

    db.recomputeJobStatusFromDocs(job.id)
  } catch {
    // Silently fail — user can generate manually from the job detail page
  }
}

app.whenReady().then(() => {
  registerIpc()
  createWindow()
  startQueueProcessor()
  scheduleNextAutoScan()

  // One-shot: normalize legacy locations to "City, REGION, CC" the first time
  // the app loads with a populated store. Idempotent — gated by a flag.
  if (!db.hasLocationsNormalized() && db.listJobs().length > 0) {
    try {
      const result = db.retrofitLocations()
      if (result.updated > 0) {
        console.log(`[startup] Normalized ${result.updated}/${result.total} job locations.`)
      }
    } catch (err) {
      console.error('[startup] Location retrofit failed:', err)
    }
  }

  // One-shot: recompute every job's status from its current documents the
  // first time the app loads after the doc-derived status rule landed. This
  // backfills statuses that drifted while the recompute was per-handler
  // only. Idempotent — gated by a flag.
  if (!db.hasStatusesRecomputed() && db.listJobs().length > 0) {
    try {
      const result = db.recomputeAllJobStatuses()
      if (result.updated > 0) {
        console.log(`[startup] Refreshed status for ${result.updated}/${result.total} jobs.`)
      }
    } catch (err) {
      console.error('[startup] Status refresh failed:', err)
    }
  }

  // One-shot: bump the global CV version so the bootstrap score pass re-scores
  // every job that's currently holding a heuristic-only fit score. This
  // self-heals the bug where the LLM scorer silently fell back to a keyword
  // overlap score and the user got a misleading number. After this runs
  // once the flag is set, so subsequent launches only re-score when the
  // user actually edits the base CV.
  if (!db.hasFitRescoreFlag() && db.listJobs().length > 0) {
    try {
      const v = db.bumpCvVersion()
      db.markFitRescored()
      console.log(`[startup] Bumped cv_version to ${v} to force fit re-score of all jobs.`)
    } catch (err) {
      console.error('[startup] CV version bump failed:', err)
    }
  }

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    stopQueueProcessor()
    app.quit()
  }
})
